import type { NextPage } from "next";
import Head from "next/head";
import { useConnect, useAccount } from "wagmi";
import { useState } from "react";

const Home: NextPage = () => {
  const [{ data: connectData, loading: isLoadingConnectData }, connect] =
    useConnect();
  const [{ data: accountData, loading: isLoadingAccountData }, disconnect] =
    useAccount({
      fetchEns: true,
    });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold">Hello world!</h1>
      {connectData?.connectors?.map((connector) => {
        return (
          <div>
            <span>{connector.name}</span>{" "}
            <button
              onClick={() => {
                connect(connector);
              }}
            >
              connect
            </button>
          </div>
        );
      })}
      <div>{accountData?.address}</div>
      {accountData?.address ? (
        <div>
          <button onClick={disconnect}>Disconnect</button>
        </div>
      ) : null}
    </div>
  );
};

export default Home;
